### ISSUE TITLE
Constant variables lack name

### ISSUE THREAD

**Issue by quanyang** [ircmaxell/php-cfg#15]
Sample code:
```
class A {
	const CONSTANT = 'constant value';
}
```
Output
```
    Terminal_Const
        value: LITERAL('constant value')
```

Should the constant name be part of the output?

**Comment by nikic** [comment]
Fixed by https://github.com/ircmaxell/php-cfg/commit/bcb27aa6381c8c457ac7f5cce1e4a362764b3b1d.
