### ISSUE TITLE
Switch Case missing conditions

### ISSUE THREAD

**Issue by quanyang** [ircmaxell/php-cfg#18]
hey @nikic, appreciate your help fixing the issues. However, if you feel that some issues shouldn't be an issue, please feel free to close them (I can modify my fork separately).

In this case, I feel that the switch statements should have some kind of condition?
Example:
```
<?php
switch ($i) {
case 0:
case 1:
case 2:
    echo "i is less than 3 but not negative";
    break;
case 3:
    echo "i is 3";
}
?>
```
Block#1
    Stmt_Switch
        targets: Block#2
        targets: Block#2
        targets: Block#2
        targets: Block#3

Block#2
    Parent: Block#1
    Terminal_Echo
        expr: LITERAL('i is less than 3 but not negative')
    Stmt_Jump
        target: Block#4

Block#3
    Parent: Block#1
    Terminal_Echo
        expr: LITERAL('i is 3')
    Stmt_Jump
        target: Block#4

Block#4
    Parent: Block#2
    Parent: Block#3
```

**Comment by nikic** [comment]
Condition and cases now visible: https://github.com/ircmaxell/php-cfg/commit/7002efe458da007e5dfe2c68e516418f259f60cd

However the way switch is compiled will not be correct if cases are not literals. Probably that case should be desugared to if chain, and the switch opcode only used for jumptable switches.

**Comment by nikic** [comment]
Switch desugaring implemented in https://github.com/ircmaxell/php-cfg/commit/7c5333dc99c08522666e78339c1060239e5831f3.
