### ISSUE TITLE
Fatal error when function block is empty, or when declaring interfaces

### ISSUE THREAD

**Issue by quanyang** [ircmaxell/php-cfg#20]
Example:
```
<?php
interface Iface  {
    function test();
}
```

Or

```
<?php
class NameOfClass  {
    function test() {
        
    }
    function doSomething() {
        echo "Hello World";
    }
}
```

Error:
```
Catchable fatal error: Argument 1 passed to PHPCfg\Visitor\DeclarationFinder::beforeTraverse() must be an instance of PHPCfg\Block, null given in /php-cfg/lib/PHPCfg/Visitor/DeclarationFinder.php on line 76
```

**Comment by nikic** [comment]
This should probably do it: https://github.com/ircmaxell/php-cfg/commit/21c299b9bb58c3f2e5584b3d846f5c827d6f1d4e Need to write some visitor tests when back home.

**Comment by quanyang** [comment]
Issue got regressed to another section of code:
```Catchable fatal error: Argument 1 passed to PHPCfg\Traverser::traverseBlock() must be an instance of PHPCfg\Block, null given, called in php-cfg/lib/PHPCfg/Traverser.php on line 35 and defined in /Users/quanyang/Projects/fyp/Research/php-cfg/lib/PHPCfg/Traverser.php on line 45```

**Comment by nikic** [comment]
Next try: https://github.com/ircmaxell/php-cfg/commit/1dbdfd216cbab7e458b096e3a22b2268455ce9e2
