### ISSUE TITLE
Script & Func structure

### ISSUE THREAD

**Issue by mwijngaard** [ircmaxell/php-cfg#28]
In 0d54187759ac945e4cf02d8c8dff82fb121192e0 you introduced the script and func structures. While I agree that it is necessary for each function to have its own variable scope, I dislike the global storing of funcs in the script (this is weird for closures or conditionally defined functions), and the fact that each function-like object now has all of the same properties:

- Functions should be identified just by namespaced name, methods should be identified by namespaced class name and method name, closures should not need to be identified by something (except when printing). 
- 'Main' functions can not have arguments or type hints
- Closures can only define their 'use' variables in the PHPCfg\Op\Expr\Closure class and not in the Func. 

All in all: do you agree with refactoring some of this change back and making the parser return a Block instead of a Script, moving the Func name to namespacedName in Function_ and namespacedClassName and methodName in ClassMethod, and removing the closure identification from the parser (this can be moved to the printer, similar to how blocks are identified)?

If you agree to this change I have one more question before I can apply this: what was the intended use of the printVars function in Printer? It's not currently used for anything.

**Comment by nikic** [comment]
What's the goal here? We need to split the CFGs of the different functions, so we need some kind of boundary between functions. Func is that boundary right now. How would this splitting be realized without Func?

You are right that handling of closures currently doesn't make sense. Closure binding has two parts: First, the variables need to be bound to the closure when it is created (this part is currently kinda-sorta represented). Second, inside the closure the values need to be bound to local variables (this part is completely missing).

As to printVars ... it does not seem very useful. The Text printer actually has a typo right in the first line: https://github.com/ircmaxell/php-cfg/blob/master/lib/PHPCfg/Printer/Text.php#L51 :/

**Comment by mwijngaard** [comment]
It's mainly about what the API should be like. I'm thinking about this because I'm trying to get Anythony's php-types to work again, and the API's have diverged a little bit as we have been developing php-cfg further. 

I think it would be better if we replace the Parser by a Generator, that generates a CFG based on an AST, and possibly by some facade object that offers directly parsing a file. Then we decouple the CFG generation from the AST parser, there is not really any reason for it to be integrated into the CFG Parser like it is now. This also takes care of the weird filename parameter that you have to pass along with the input string.

Whether we do this or not, I think it is weird that the 'main' execution scope is a Func. It is not the same as a function, as it has no parameters and its scope is whatever scope included it. I therefore think it would be better to have it be a Block.

**Comment by nikic** [comment]
> I think it would be better if we replace the Parser by a Generator, that generates a CFG based on an AST, and possibly by some facade object that offers directly parsing a file. Then we decouple the CFG generation from the AST parser, there is not really any reason for it to be integrated into the CFG Parser like it is now. This also takes care of the weird filename parameter that you have to pass along with the input string.

Agree with at least having the option of passing the AST directly. However I don't think this will get rid of the filename parameter, as we still need it for things like `__FILE__` and attributes. Also agree with "Parser" being a misnomer. This class is really an IR compiler (though generator or constructor sounds fine as well).

> Whether we do this or not, I think it is weird that the 'main' execution scope is a Func. It is not the same as a function, as it has no parameters and its scope is whatever scope included it. I therefore think it would be better to have it be a Block.

The motivation for having pseudo-main as a Func is basically this: If you run SSA algorithms, it generally does not matter (beyond lattice initializations etc) whether the function is a function, closure, method or even pseudo-main code. You want to treat everything uniformly. For the most part you will need the CFG and parameters, and potentially the class scope. A uniform interface that does not encapsulate these as an object (here Func) will need to pass these along as separate parameters, and the calling code will need to treat the pseudo-main code differently from anything else.

The motivation for Script is that you probably want to apply analysis passes to all functions in the script and this provides a simple way of doing so, without having to either first extract the functions in a separate pass, or use a function worklist.

**Comment by mwijngaard** [comment]
> Agree with at least having the option of passing the AST directly. However I don't think this will get rid of the filename parameter, as we still need it for things like __FILE__ and attributes. Also agree with "Parser" being a misnomer. This class is really an IR compiler (though generator or constructor sounds fine as well).

But if we link in the original AST node, through an 'original' attribute, then that node will have the filename. In any case I don't think resolving `__FILE__ `should be part of the CFG creation process itself. This is evaluation, and immediately resolving hard-links the CFG to the file that originally contained it. While that may be what you want some of the time, this is definately not the case all the time. As an example: a dependence graph, like the one i'm working on, can be used for semantic clone by looking at the dependence structure. But if magic properties like `__FILE__ `get resolved right away, then a clone containing these can never be detected because the filename will always be different. Perhaps storing the filename in the Script object would be a better way? 

> The motivation for having pseudo-main as a Func is basically this: If you run SSA algorithms, it generally does not matter (beyond lattice initializations etc) whether the function is a function, closure, method or even pseudo-main code. You want to treat everything uniformly. For the most part you will need the CFG and parameters, and potentially the class scope. A uniform interface that does not encapsulate these as an object (here Func) will need to pass these along as separate parameters, and the calling code will need to treat the pseudo-main code differently from anything else.

But couldnt any algorithm that treats pseudo-main and functions as the same just as well have a block as input? That is basically their shared concern. Anyhow, I don't really care about this too much, but the name property of the Funcs is currently inconsistent, with Functions getting a Name object, class methods getting a method name string and class Literal object, and closures and pseudo-main getting special strings.

> The motivation for Script is that you probably want to apply analysis passes to all functions in the script and this provides a simple way of doing so, without having to either first extract the functions in a separate pass, or use a function worklist. 

Fair enough.

**Comment by mwijngaard** [comment]
> Agree with at least having the option of passing the AST directly. However I don't think this will get rid of the filename parameter, as we still need it for things like __FILE__ and attributes. Also agree with "Parser" being a misnomer. This class is really an IR compiler (though generator or constructor sounds fine as well).

But if we link in the original AST node, through an 'original' attribute, then that node will have the filename. In any case I don't think resolving `__FILE__ `should be part of the CFG creation process itself. This is evaluation, and immediately resolving hard-links the CFG to the file that originally contained it. While that may be what you want some of the time, this is definately not the case all the time. As an example: a dependence graph, like the one i'm working on, can be used for semantic clone detection by looking at the dependence structure. But if magic properties like `__FILE__ `get resolved right away, then a clone containing these can never be detected because the filename will always be different. Perhaps storing the filename in the Script object would be a better way? 

> The motivation for having pseudo-main as a Func is basically this: If you run SSA algorithms, it generally does not matter (beyond lattice initializations etc) whether the function is a function, closure, method or even pseudo-main code. You want to treat everything uniformly. For the most part you will need the CFG and parameters, and potentially the class scope. A uniform interface that does not encapsulate these as an object (here Func) will need to pass these along as separate parameters, and the calling code will need to treat the pseudo-main code differently from anything else.

But couldnt any algorithm that treats pseudo-main and functions as the same just as well have a block as input? That is basically their shared concern. Anyhow, I don't really care about this too much, but the name property of the Funcs is currently inconsistent, with Functions getting a Name object, class methods getting a method name string and class Literal object, and closures and pseudo-main getting special strings.

> The motivation for Script is that you probably want to apply analysis passes to all functions in the script and this provides a simple way of doing so, without having to either first extract the functions in a separate pass, or use a function worklist. 

Fair enough.

**Comment by mwijngaard** [comment]
> Agree with at least having the option of passing the AST directly. However I don't think this will get rid of the filename parameter, as we still need it for things like __FILE__ and attributes. Also agree with "Parser" being a misnomer. This class is really an IR compiler (though generator or constructor sounds fine as well).

But if we link in the original AST node, through an 'original' attribute, then that node will have the filename. In any case I don't think resolving `__FILE__ `should be part of the CFG creation process itself. This is evaluation, and immediately resolving hard-links the CFG to the file that originally contained it. While that may be what you want some of the time, this is definately not the case all the time. As an example: a dependence graph, like the one i'm working on, can be used for semantic clone detection by looking at the dependence structure. But if magic properties like `__FILE__ `get resolved right away, then a clone containing these can never be detected because the filename will always be different. Perhaps storing the filename in the Script object would be a better way? 

> The motivation for having pseudo-main as a Func is basically this: If you run SSA algorithms, it generally does not matter (beyond lattice initializations etc) whether the function is a function, closure, method or even pseudo-main code. You want to treat everything uniformly. For the most part you will need the CFG and parameters, and potentially the class scope. A uniform interface that does not encapsulate these as an object (here Func) will need to pass these along as separate parameters, and the calling code will need to treat the pseudo-main code differently from anything else.

But couldnt any algorithm that treats pseudo-main and functions as the same just as well have a block as input? That is basically their shared concern. Anyhow, I don't really care about this too much, but the name property of the Funcs is currently inconsistent, with Functions getting a Name object, class methods getting a method name string and class Literal object, and closures and pseudo-main getting special strings.

> The motivation for Script is that you probably want to apply analysis passes to all functions in the script and this provides a simple way of doing so, without having to either first extract the functions in a separate pass, or use a function worklist. 

Fair enough.

**Comment by mwijngaard** [comment]
> Agree with at least having the option of passing the AST directly. However I don't think this will get rid of the filename parameter, as we still need it for things like __FILE__ and attributes. Also agree with "Parser" being a misnomer. This class is really an IR compiler (though generator or constructor sounds fine as well).

But if we link in the original AST node, through an 'original' attribute, then that node will have the filename. In any case I don't think resolving `__FILE__ `should be part of the CFG creation process itself. This is evaluation, and immediately resolving hard-links the CFG to the file that originally contained it. While that may be what you want some of the time, this is definately not the case all the time. As an example: a dependence graph, like the one i'm working on, can be used for semantic clone detection by looking at the dependence structure. But if magic properties like `__FILE__ `get resolved right away, then a clone containing these can never be detected because the filename will always be different. Perhaps storing the filename in the Script object would be a better way? 

> The motivation for having pseudo-main as a Func is basically this: If you run SSA algorithms, it generally does not matter (beyond lattice initializations etc) whether the function is a function, closure, method or even pseudo-main code. You want to treat everything uniformly. For the most part you will need the CFG and parameters, and potentially the class scope. A uniform interface that does not encapsulate these as an object (here Func) will need to pass these along as separate parameters, and the calling code will need to treat the pseudo-main code differently from anything else.

But couldnt any algorithm that treats pseudo-main and functions as the same just as well have a block as input? That is basically their shared concern. Anyhow, I don't really care about this too much, but the name property of the Funcs is currently inconsistent, with Functions getting a Name object, class methods getting a method name string and class Literal object, and closures and pseudo-main getting special strings.

> The motivation for Script is that you probably want to apply analysis passes to all functions in the script and this provides a simple way of doing so, without having to either first extract the functions in a separate pass, or use a function worklist. 

Fair enough.

**Comment by nikic** [comment]
> But if we link in the original AST node, through an 'original' attribute, then that node will have the filename.

The AST nodes don't contain the file name either ... at least not by default.

> In any case I don't think resolving `__FILE__` should be part of the CFG creation process itself. This is evaluation, and immediately resolving hard-links the CFG to the file that originally contained it. While that may be what you want some of the time, this is definately not the case all the time. As an example: a dependence graph, like the one i'm working on, can be used for semantic clone detection by looking at the dependence structure.

Good point. Evaluation of magic constants is a separate concern from SSA construction, and, as you point out, it may be useful to avoid this evaluation. We could drop it here and provide a separate pass for basic constant folding...

> But couldnt any algorithm that treats pseudo-main and functions as the same just as well have a block as input? That is basically their shared concern.

Sure. The issue is that any such algorithm would likely also need the parameters (for initialization) and might also need the scope (to determine possible targets of calls, for example). For error messages or analysis output it might also also need the name of the function. At which point we'd be basically passing all the members of the Func object as arguments to the analysis pass :)

> Anyhow, I don't really care about this too much, but the name property of the Funcs is currently inconsistent, with Functions getting a Name object, class methods getting a method name string and class Literal object, and closures and pseudo-main getting special strings.

Duh, that wasn't intentional. I've changed name to always be a string in https://github.com/ircmaxell/php-cfg/commit/827d644cc5864b1bb6ec05a925256f98252d37e4. I've also added a flags property in https://github.com/ircmaxell/php-cfg/commit/69ae46aa441e7b0dd01a95a990ffd1ecc7753cd0 which can be used to distinguish closures (among other things).

For consistency should probably change the class name to a string as well. PHP internally uses a `null` name for pseudo-main, that seems like a better choice than directly using `#{main}`.

**Comment by mwijngaard** [comment]
Ok, clear. Then i consider this issue resolved.
