### ISSUE TITLE
Uncaught exception 'RuntimeException' with message 'Unknown Stmt Node Encountered : Stmt_Nop' in /Library/WebServer/Documents/shiw/lib/PHPCfg/Parser.php:148

### ISSUE THREAD

**Issue by xukaiyi** [ircmaxell/php-cfg#29]
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unknown Stmt Node Encountered : Stmt_Nop' in /Library/WebServer/Documents/shiw/lib/PHPCfg/Parser.php:148
Stack trace:
#0 /Library/WebServer/Documents/shiw/lib/PHPCfg/Parser.php(131): PHPCfg\Parser->parseNode(Object(PhpParser\Node\Stmt\Nop))
#1 /Library/WebServer/Documents/shiw/lib/PHPCfg/Parser.php(376): PHPCfg\Parser->parseNodes(Array, Object(PHPCfg\Block))
#2 /Library/WebServer/Documents/shiw/lib/PHPCfg/Parser.php(359): PHPCfg\Parser->parseIf(Object(PhpParser\Node\Stmt\If_), Object(PHPCfg\Block))
#3 /Library/WebServer/Documents/shiw/lib/PHPCfg/Parser.php(145): PHPCfg\Parser->parseStmt_If(Object(PhpParser\Node\Stmt\If_))
#4 /Library/WebServer/Documents/shiw/lib/PHPCfg/Parser.php(131): PHPCfg\Parser->parseNode(Object(PhpParser\Node\Stmt\If_))
#5 /Library/WebServer/Documents/shiw/lib/PHPCfg/Parser.php(376): PHPCfg\Parser->parseNodes(Array, Object(PHPCfg\Block))
#6 /Library/WebServer/Documents/shiw/lib/PHPCfg/Parser.php(385): PHPCfg\Parser->parseIf(Object(PhpP in /Library/WebServer/Documents/shiw/lib/PHPCfg/Parser.php on line 148

**Comment by nikic** [comment]
Fixed by https://github.com/ircmaxell/php-cfg/commit/08a8dee7e593023bd48c260f94f2190388ec85a6, thanks for the report!
