### ISSUE TITLE
packagist is not synchronized with github

### ISSUE THREAD

**Issue by eric-therond** [ircmaxell/php-cfg#51]
Hello,
I don't know why packagist is not automatically synchronized with github ?
last version of php-cfg on github : d0e9723
last version of php-cfg on packagist : 7f9da3c

Eric

**Comment by nikic** [comment]
@ircmaxell Can you check this? The repo is probably missing the travis hook. I don't have access to the hook admin here.

**Comment by ircmaxell** [comment]
Fixed, not sure what happened here, but it is updating now...
