### ISSUE TITLE
Syntax Error in PHPCfg/Parser.php

### ISSUE THREAD

**Issue by tenje** [ircmaxell/php-cfg#56]
There is a syntax error in 'PHPCfg/Parser.php':

Parse error: syntax error, unexpected ')' in line 310

PHP version: 7.2

**Comment by tenje** [comment]
Can be fixed by removing the ',' (Comma) after 'null' in line 387.

**Comment by villfa** [comment]
This syntax is valid since PHP-7.3 ( https://www.php.net/manual/en/migration73.new-features.php#migration73.new-features.core.trailing-commas ) and this library requires at least PHP-7.4.
