### ISSUE TITLE
Unknown Node Encountered : Stmt_GroupUse

### ISSUE THREAD

**Issue by eric-therond** [ircmaxell/php-cfg#58]
Hello 
when analyzing 
`use foo\math\{ Math, const PI, function sin, function cos, function cosh };`

I have this error :

> PHP Fatal error:  Uncaught RuntimeException: Unknown Node Encountered : Stmt_GroupUse in /home/eric/ircmaxell/php-cfg/lib/PHPCfg/Parser.php:170
Stack trace:
#0 /home/eric/ircmaxell/php-cfg/lib/PHPCfg/Parser.php(106): PHPCfg\Parser->parseNode(Object(PhpParser\Node\Stmt\GroupUse))
#1 /home/eric/ircmaxell/php-cfg/lib/PHPCfg/Parser.php(127): PHPCfg\Parser->parseNodes(Array, Object(PHPCfg\Block))
#2 /home/eric/ircmaxell/php-cfg/lib/PHPCfg/Parser.php(91): PHPCfg\Parser->parseFunc(Object(PHPCfg\Func), Array, Array)
#3 /home/eric/ircmaxell/php-cfg/lib/PHPCfg/Parser.php(76): PHPCfg\Parser->parseAst(Array, './tests/negativ...')
#4 /home/eric/tests/testphpcfg.php(10): PHPCfg\Parser->parse('<?php\n\nuse foo\\...', './tests/negativ...')
#5 {main}
  thrown in /home/eric/ircmaxell/php-cfg/lib/PHPCfg/Parser.php on line 170

I have proposed a fix [here](https://github.com/ircmaxell/php-cfg/pull/52/commits/913cfdbfcaf78e6d220d6f65a50d3998fa7c22c4)

**Comment by kaystrobach** [comment]
Same here using prog pilot

**Comment by kaystrobach** [comment]
See https://github.com/designsecurity/progpilot/issues/20#issuecomment-619532511 for details

**Comment by ircmaxell** [comment]
All you need to do is add a blank function inside the Parser class:

```php
    protected function parseStmt_GroupUse(Stmt\GroupUse $node)
    {
        // ignore use statements, since names are already resolved
    }
```

If that works, would you be willing to send a PR?

**Comment by kaystrobach** [comment]
Sill try the next days

**Comment by ircmaxell** [comment]
Just following up, were you able to test?
