### ISSUE TITLE
ArrayDimFetch usages are not tracked

### ISSUE THREAD

**Issue by silverfoxy** [ircmaxell/php-cfg#62]
I noticed that when we have an ArrayDimFetch, on the same array and same dimension, the usage is not tracked.
In this case:
```php
<?php

$b = 'home.php';

$target_blacklist = array('import.php', 'export.php');

if (!in_array($b, $target_blacklist)) {
    include $b;
    exit;
}
```
We can see that $b has two usages and in_array is listed as one of the usages of $b. But in the following case:
```php
<?php

$a = ['index.php', 'home.php'];

$target_blacklist = array('import.php', 'export.php');

if (!in_array($a[1], $target_blacklist)) {
    include $a[1];
    exit;
}
```
The usages of $a[1] is only the include.

**Comment by silverfoxy** [comment]
Is this the expected behavior? 
As $b would be referencing the same variable, but each time we perform an arraydimfetch we have a different expression?

**Comment by ircmaxell** [comment]
As long as `$a` is tracked between them, then yes, that is intended behavior. 

The reason is that each array fetch may be non-deterministic, so therefore we can't 100% assume that `$a[1]` will be the same in both calls. So it generates a separate fetch for each.
