### ISSUE TITLE
Display the block's source file and line number information when generating the .dot file

### ISSUE THREAD

**Issue by inksong** [ircmaxell/php-cfg#74]
Your job is a great job! Thank you very much for your contribution!
By the way, do you have plans to continue to maintain this project?
Taking into account the increasing popularity of automated testing, 
our project team will provide security analysis for PHP language projects, where your code is used!
Unfortunately, there is a lack of PHP developers among our team members. 

If the php-cfg project can display the block's source file and line number information when generating the .dot file, 
we can automatically integrate your project! 
If it is not very troublesome, I wonder if you are willing to add this feature?
Thx a lot!

**Comment by ircmaxell** [comment]
Each `Operand` should have a filename attribute (along with line number and such). The attributes are `filename` and `startLine`. It should be pretty easy to add it to the generated dot file, which is generated in https://github.com/ircmaxell/php-cfg/blob/master/lib/PHPCfg/Printer/GraphViz.php
